name: Docker Image for GHCR
on:
  push:
    branches: [development]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
           
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push the docker image
        run: |
          docker build . --tag ghcr.io/ramgrg/sonar-green-for-loops:latest
          docker push ghcr.io/ramgrg/sonar-green-for-loops:latest

  
