name: Maven Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Publish to GitHub Packages Apache Maven
      run : |
            mvn -B package --file static-code-analysis/pom.xml
            mkdir artifacts && cp /home/runner/work/static-code-analysis/static-code-analysis/static-code-analysis/target/*.jar artifacts
            cd artifacts && ls
    - name: Save artifact 
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: artifacts
